# Cipher 1

# This profile works:
# Only ciphers defined in "application.yml" are available  

server:
  ssl:
    keyStoreType: 'PKCS12'
    # we use a keystore location which is never tracked by git. 
    # see dev-create_localhost_certificate.sh and dev-ensure_localhost_certificate.sh
    key-store: 'classpath:test-certificate.p12'
    key-store-password: '123456'
    key-alias: 'tomcat'
