spring: 
   application:
     name: demo
     
# --------------------------------------
# - SSL setup  (default)
# --------------------------------------
server:
  # port is defined for in other profiles (cipher1/cipher2)
  error:
    path: "/error"
  ssl:
    enabled: true # always enabled
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    # keystore, alias etc. is defined for in other profiles (cipher1/cipher2)
    ciphers: 
     - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
     - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
     - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
     - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
     - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
     - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
     - TLS_AES_128_GCM_SHA256
     - TLS_AES_256_GCM_SHA384
     - TLS_AES_128_CCM_SHA256
     - ECDHE-ECDSA-CHACHA20-POLY1305-SHA256
     - ECDHE-ECDSA-CHACHA20-POLY1305
     - ECDHE-ECDSA-AES256-SHA384
     - ECDHE-ECDSA-AES128-SHA256
     - ECDHE-RSA-CHACHA20-POLY1305
     - DHE-RSA-AES256-GCM-SHA384
     - DHE-RSA-AES128-GCM-SHA256
     - ECDHE-RSA-AES256-GCM-SHA384
     - ECDHE-RSA-AES128-GCM-SHA256


